### ISSUE TITLE
Child windows not visible

### ISSUE THREAD

**Issue by JasonMiesionczek** [ilovecookieee/Glorious-Dotfiles#1]
When an application opens a child window, such as a save or open dialog, the window is visible in the bar on top, but not the actual window. Click on the window in the top bar does nothing, cannot alt-tab to it either.

**Comment by ilovecookieee** [comment]
Are you using the git version of awesome? I think there are some API changes that   causes this issues. Even the icons in tasklist are missing. Anyway, I will try to port it to the git branch sooner or later.

**Comment by ilovecookieee** [comment]
Found the culprit! It is the shape property in dialogs rule in rules.lua. Just remove it and it will fix the problem! Cheers!

**Comment by JasonMiesionczek** [comment]
Confirmed that fixed it, thanks! :)
