### ISSUE TITLE
[Floppy] Unable to find 'rofile'

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#14]
**Hello there !** :smiley:
I'm trying to use your "Floppy" theme and it's really nice and all, but I'm stuck at some things.

**( 1 )** When I press the "Search" icon on the top-right corner beside the notification icon, or when I 
press Super+E, I get the following message :

> Failed to execute: 'rofind'
> Error: 'Failed to execute child process "rofind" (No such file or directory)'

I think I installed all the dependencies correctly (including awesome-git and rofi-git) from AUR (I'm on Manjaro). Do I need to edit any config files or such to make the Applications Dashboard function as in your beautiful screenshots ? If so then can you please help me with them? I'm completely new to AwesomeWM.> I think I installed all the dependencies correctly (including awesome-git and rofi-git) from AUR (I'm on Manjaro). Do I need to edit any config files or such to make the Applications Dashboard function as in your beautiful screenshots ? If so then can you please help me with them? I'm completely new to AwesomeWM.

**( 2 )** The brightness control slider in the Quick Settings Dashboard doesn't seem to do anything. Is that a config issue too ? Please help me edit that as well. I have yet to test the Volume slider though, as I don't have any music on the PC at the moment. Will update on the Volume control soon.

**Thanks for being patient with me.** :smile:

**Comment by ilovecookieee** [comment]
> ( 1 ) When I press the "Search" icon on the top-right corner beside the notification icon, or when I
press Super+E, I get the following message :

Strange, the rofi configuration file should be in your [`$HOME/.config/awesome/configuration/rofi/appmenu/`](https://github.com/ilovecookieee/Glorious-Dotfiles/blob/master/config/awesome/floppy/configuration/rofi/appmenu/drun.rasi)

> Do I need to edit any config files or such to make the Applications Dashboard function as in your beautiful screenshots ? If so then can you please help me with them? I'm completely new to AwesomeWM.

Yep, you need to, depending on your screen resolution. I configure the dashboard to work on my `1366x768` so if you have bigger monitor, you must change that haha. In that case change these [lines](https://github.com/ilovecookieee/Glorious-Dotfiles/blob/900b9bdf9f19b181abba59a07368bfbcd6d103ed/config/awesome/floppy/configuration/rofi/appmenu/drun.rasi#L21-L22)

> The brightness control slider in the Quick Settings Dashboard doesn't seem to do anything. Is that a config issue too ?

The brightness slider uses `xbacklight`. It works on my intel graphics, but only with `uxa` and `sna` as drivers, it doesn't work on `modesetting`. So if you're using `modesetting` as intel driver or if you use different graphics card, you should change `xbacklight`.

**Comment by AIsage** [comment]
> Yep, you need to, depending on your screen resolution. I configure the dashboard to work on my 1366x768 so if you have bigger monitor, you must change that haha. In that case change these lines

My screen is 1366x768 too, so I think I should leave that unchanged.

> The brightness slider uses xbacklight. It works on my intel graphics, but only with uxa and sna as drivers, it doesn't work on modesetting. So if you're using modesetting as intel driver or if you use different graphics card, you should change xbacklight.

Thanks, I'll try that.

I've updated the post to the right error message.

> Strange, the rofi configuration file should be in your $HOME/.config/awesome/configuration/rofi/appmenu/

Thanks, I'll see if it's there.

**Comment by AIsage** [comment]
[mhwd-msg.txt](https://github.com/ilovecookieee/Glorious-Dotfiles/files/4000108/mhwd-msg.txt)

Here's what comes when I type "mhwd -l -d", if it helps identify what drivers I have.

**Comment by ilovecookieee** [comment]
Oof, you're using nvidia. Sorry, I cannot help you with that. I don't have enough knowledge about troubleshooting nvidia because I never have one.  You should check/research on how to adjust your backlight using terminal. The setup uses `xbacklight`. Try running `xbacklight -set 10` and `xbacklight -set 100`, see if your brightness will adjust.

**Comment by AIsage** [comment]
Actually, I didn't install `xbacklight` before (because it wasn't mentioned as a dependency on the front page...). After I installed it, the brightness slider started to function as it should. Thanks. :smile:
.
But the appmenu still shows the error :
> Failed to execute: 'rofind'
> Error: 'Failed to execute child process "rofind" (No such file or directory)'

I've confirmed the presence of `drun.rasi` where it's supposed to be, but still the error pops up.
.
Also, could you please tell me which file I need to edit to change the web search dashboard engine from Google to Ecosia ? The URL for an Ecosia search is like `https://www.ecosia.org/search?q=%s`

**Thanks for helping me out. You're very patient.** :cat:

**Comment by AIsage** [comment]
And just to let you know, the volume slider doesn't seem to work too... I don't see any pulseaudio slider on the top bar either. I expected it to be where the Redshift, Xfce4 Power Manager, Network Manager icons are.

**Comment by ilovecookieee** [comment]
>  could you please tell me which file I need to edit to change the web search dashboard engine from Google to Ecosia

Add your search engine of choice [here](https://github.com/ilovecookieee/Glorious-Dotfiles/blob/900b9bdf9f19b181abba59a07368bfbcd6d103ed/config/awesome/floppy/configuration/rofi/sidebar/rofi-web-search.py#L40-L510

> volume slider

The setup uses amixer to adjust volume. Make sure to install alsa-utils.


> I don't see any pulseaudio slider on the top bar either

It's because you need to install it and run it on startup. That is not part of my setup.

**Comment by AIsage** [comment]
Thanks, the volume slider works great now. The problem was that the audio channel was set to speakers. I needed it on headphones. Sorry.

The app dashboard still doesn't seem to work though.

**Comment by AIsage** [comment]
Finally got everything to work (I guess).
The menu appears fine after installing `rofi-scripts` . Maybe add `xbacklight` and `rofi-scripts` to the dependency list?

**Comment by AIsage** [comment]
And again, sorry.
1) How to set custom picture beside username?
2) How to fix the connection error for both the weather and gmail widgets? I am connected to the internet.

**Comment by ilovecookieee** [comment]
> Maybe add xbacklight and rofi-scripts to the dependency list?

Well, `xbacklight` is a must on a fresh install so I assume that it's already installed. And `rofi-scripts` is not required to install in ArchLinux and I don't even know that it exists lol. 

> How to set custom picture beside username?

You can find it in widgets folder named `user-profile`. Just edit the lua file.

>How to fix the connection error for both the weather and gmail widgets? I am connected to the internet.

You can find it in widgets folder named `weather` and `gmail`. Just edit the lua file and add your credentials.

**Comment by AIsage** [comment]
Thanks a lot for your time and helping me set up this beautiful desktop. 😊
