### ISSUE TITLE
[Suggestion] Backlight Control App

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#16]
Just a suggestion to try to change your brightness slider to use `light` instead of `xbacklight` as it's compatible with more diverse systems. [elenapan's dotfiles](https://github.com/elenapan/dotfiles/blob/master/config/awesome/evil/brightness.lua) use `light` so I think you can reuse code from there if that's ok.

**Comment by ilovecookieee** [comment]
Yep, I tried using `light` before. But right now, I'll stay with `xbacklight`. Thank you for suggestion tho. I'll consider it if `xbacklight` stops working haha
