### ISSUE TITLE
[Floppy] Rofi menu problems

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#18]
![Screenshot_2020-01-02_16-53-39](https://user-images.githubusercontent.com/50134239/71670021-d4ff4700-2d98-11ea-8f91-e70dba2eb369.png)

The App Drawer shouldn't look like this, should it ? It looks quite different from your screenshots.
Any config file I need to change ?

_Manjaro Awesome, Screen res. : 1366x768 (14")_

**Comment by AIsage** [comment]
Also, any GUI app that needs authentication says "Authentication Failed" even without asking for password. This happens after installing the theme but not before. Like, installing software through pamac-gtk fails but if I use it through kitty terminal, it works fine.

**Comment by ilovecookieee** [comment]
> The App Drawer shouldn't look like this, should it

No lol. The setup uses the git master branch. And the configuration for that is in `$HOME/.config/awesome/configuration/rofi/appmenu/drun.rasi`

> Also, any GUI app that needs authentication says "Authentication Failed" even without asking for password. 

I think the setup have nothing to do with it. More like you don't have polkit installed. Make sure that you have `gnome-polkit` or something installed.

**Comment by AIsage** [comment]
Installing `polkit-gnome` fixes the authentication issue.

I'll close this issue for now and try to figure out how to fix the menu.

Thanks for the help.

**Comment by AIsage** [comment]
Ok, I was able to fix the menu issue too.
It seems there were residue files from the non-git installation of rofi (installed by default on Manjaro Awesome). I just had to remove those to make the App Drawer look like in your screenshots.

Thanks again.

**Comment by AIsage** [comment]
A new problem... 😐
Right-clicking the desktop doesn't bring up the application list anymore. Any solution please?

**Comment by ilovecookieee** [comment]
> Any solution please?

Uncomment the `require('module.menu')` in `rc.lua`.

**Comment by AIsage** [comment]
> Uncomment the `require('module.menu')` in `rc.lua`.

That worked fine. Thanks 😊
