### ISSUE TITLE
[Suggestion] Floating Layout

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#19]
![Screenshot_2020-01-04_10-17-00](https://user-images.githubusercontent.com/50134239/71759726-77274800-2edb-11ea-9c50-fddce9adf9e0.png)

When I press the hotkey to Toggle Floating, this happens and I can't resize kitty because the titlebar is hidden behind the Dash bar.

It'd be nice if there was a floating layout that'd float all windows with reasonable size. It's there by default on Manjaro Awesome, but it's not there after overwriting with Floppy.

If you don't implement it, could you please tell me how can I add it myself ? Which files will I have to edit and what snippets do I put in ?

**Comment by ilovecookieee** [comment]
Try this:

```lua
_G.client.connect_signal('property::floating', function(c)
  if c.instance then
    -- Dont centralized Quake terminal and clients with skip_center property
    if c.instance ~= 'QuakeTerminal' and not c.skip_center then
      c.width = 650
      c.height = 350
      awful.placement.centered(c)
    end
  end
end)
```

Add this on:

`$HOME/.config/awesome/module/decorate-client.lua`

I think you can also set the client's width and height in the rules.

**Comment by ilovecookieee** [comment]
> I can't resize kitty because the titlebar is hidden behind the Dash bar.

About that, you can resize floating clients by pressing `super key`  + `right mouse button` 

And move it by `super key` + `LMB`

**Comment by AIsage** [comment]
Thanks a lot. That worked fine for what I needed to do. :smiley: 

Closing issue.
