### ISSUE TITLE
attempt to perform arithmetic

### ISSUE THREAD

**Issue by iskmar** [ilovecookieee/Glorious-Dotfiles#2]
Hello, I am getting an error saying attempt to perform arithmetic on a table value(local'width').
/usr/share/awesome/lib/gears/shape.lua:69.
I only copied awesome folder in .config and getting this error. I can not reproduce the problem though.

**Comment by ilovecookieee** [comment]
When are you getting this message? I'm afraid I cannot help you without much information. Make sure to install the latest awesome or the git branch.

**Comment by iskmar** [comment]
it's mostly on pop-up windows like copying,confirming etc... I'll try installing the git version and later post an update of what's happening.

**Comment by ilovecookieee** [comment]
I reproduced it when I installed the stable version. The git version should fix the problem.

**Comment by iskmar** [comment]
Yes,that solved it for me as well. I am now getting a different problem with blur effects and maim not taking SS-s . Should i post in here or open different issue?

**Comment by ilovecookieee** [comment]
Glad it worked. Just open a new issue mate

**Comment by Sventra** [comment]
I'm getting the same error when using apps like pamac whenever they request root or simply opening xfce power manager

**Comment by ilovecookieee** [comment]
@Sventra Use the git master branch, it'll fix it. But if you want to use the stable version, comment out the backdrop module in rc.lua.

**Comment by Sventra** [comment]
> @Sventra Use the git master branch, it'll fix it. But if you want to use the stable version, comment out the backdrop module in rc.lua.

Well, the error still pops up now, but it doesn't have the dark backdrop anymore
Also, I am already using the git master branch and I'm not aware of a stable one existing, I downloaded this just yesterday
