### ISSUE TITLE
[Floppy] Gmail Widget doesn't work

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#20]
Gmail widget still doesn't seem to work. It just shows "Check Internet Connection". I've edited in my credentials into the. `~/.config/awesome/widget/gmail/init.lua` file as you instructed. The connection error is still persistent.

**Comment by ilovecookieee** [comment]
Hmm. Strange. Try creating an app password [here](https://myaccount.google.com/apppasswords). Then use the generated password in the widget.

**Comment by AIsage** [comment]
![image](https://user-images.githubusercontent.com/50134239/71909765-d8c90a00-319a-11ea-8f61-6073e5c858ca.png)

When I click your link, it gives me an error like this...

**Comment by AIsage** [comment]
Maybe the service is unavailable in my region ?

So... no other way to make it work ?

**Comment by AIsage** [comment]
Yep, App Password does the trick. Now the Gmail widget works as expected.

Thanks a bunch. 😊
