### ISSUE TITLE
[Suggestion] gmail widget name

### ISSUE THREAD

**Issue by poiuedws** [ilovecookieee/Glorious-Dotfiles#21]
The gmail widget is just an IMAP client, therefore should work with almost any mail service,therefore i suggest renaming the widget and changing the icon.

**Comment by ilovecookieee** [comment]
[Done](https://github.com/ilovecookieee/Glorious-Dotfiles/commit/5fe0ac7af0f95518da89520e978179636695b664)! Thanks for the suggestion!
