### ISSUE TITLE
[Floppy] Make GTK apps transparent and blur background

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#22]
In your video of Floppy Workflow, xfce4 power manager, which is a GTK app, had the same transparent blur effects as Qt apps. How did you do this ? Mine looks like the usual GTK solid theme.
.
.
.
Also, just letting you know, picom does the same thing as compton-tryone. And picom replaces Compton. Maybe list picom as alternative dependency to compton-tryone ?

**Comment by ilovecookieee** [comment]
> In your video of Floppy Workflow, xfce4 power manager, which is a GTK app, had the same transparent blur effects as Qt apps. How did you do this ? 

It's just a [regular gtk theme](https://github.com/ilovecookieee/Glorious-Dotfiles/tree/master/misc/gtk/oomox-Vanish) I created using oomox. I set xfce-power-manager's opacity in `compton.conf` to **80** then enable the kawase-blur effect.

> Maybe list picom as alternative dependency to compton-tryone ?

I'll do it after tryone's picom feature/dual_kawase branch is merged to yshui's.

**Comment by AIsage** [comment]
Ok, thanks again :smiley:

**Comment by xieve** [comment]
This should probably be mentioned somewhere in the wiki ^^

**Comment by manilarome** [comment]
> This should probably be mentioned somewhere in the wiki ^^

Yes, will do. I forgot about putting this in the wiki because I'm focusing on qt apps right now haha. Will update later. Thanks for suggestion!
