### ISSUE TITLE
[Floppy] Kitty transparency and blur

### ISSUE THREAD

**Issue by AIsage** [ilovecookieee/Glorious-Dotfiles#23]
Sorry for bothering you so frequently, but... How to setup transparency and blur on Kitty terminal like in your screenshots ?

**Comment by AIsage** [comment]
Also, after updating your theme (reinstalling using latest files), the right-click menu doesn't appear anymore. Do you know a fix ?

**Comment by AIsage** [comment]
Sorry, found it. Edited the opacity rules in `~/.config/awesome/configuration/compton.conf`.

**Comment by ChapelCone** [comment]
Hi, I have a similar issue, except there is no config file in `~/.config/awesome/configuration/compton.conf`I do have a config flie under `~/.config/awesome/configuration/compton.conf` is this the same thing? If not, how can I make kitty transparent and have blur?

**Comment by manilarome** [comment]
Hi @ChapelCone . Compton is unmaintained right now, so we're using `picom` now([picom-tryone](https://aur.archlinux.org/packages/picom-tryone-git/) to be exact). Picom is a fork of compton and the configuration file is now called `picom.conf`. :)

**Comment by ChapelCone** [comment]
Hi, @manilarome . Thanks for the reply. That makes more sense, I was able to go into the picom config file and change the opacity of kitty, however that changes the opacity of the entire window, including the text. I just want the terminal to be blurred like the example images. 

The changed variable: 
```
opacity-rule = [ 
	"80:class_g = 'URxvt'",
	"80:class_g = 'UXTerm'",
	"80:class_g = 'XTerm'",
	"80:class_g = 'kitty'",
```

Thanks!

**Comment by manilarome** [comment]
Just leave kitty with 100 opacity in picom then change it's background opacity in its main [configuration](https://github.com/manilarome/the-glorious-dotfiles/blob/88fff8094bd896d09f6edd6d47feb500de3d2168/config/kitty/kitty.conf#L58).

**Comment by ChapelCone** [comment]
@manilarome That worked, thank you!
