### ISSUE TITLE
Blur effects

### ISSUE THREAD

**Issue by iskmar** [ilovecookieee/Glorious-Dotfiles#3]
Rofi not spawning in fullscreen. Maim not taking SS-s. Some blur defects when trying to copy items.
![IMG_20191015_021342](https://user-images.githubusercontent.com/15051230/66792417-e010ac80-eef8-11e9-9ef8-4835647a35a5.jpg)
![IMG_20191015_021620](https://user-images.githubusercontent.com/15051230/66792418-e0a94300-eef8-11e9-8da5-db734ee20716.jpg)
![IMG_20191015_025219](https://user-images.githubusercontent.com/15051230/66792419-e0a94300-eef8-11e9-8aff-3d5a00469f96.jpg)

Sorry for the poor quality. Had to take pictures with my phone.
P.S. I am a real newb when it comes to awesomeWM and Linux, so I might've done something stupid.

**Comment by ilovecookieee** [comment]
Ah yes the rofi is only configured to work out of the box in a 1366x768 resolution, so you should tweak it in the `$HOME/.config/awesome/configuration/rofi/appmenu/drun.rasi`. And as of the blur, you can disable it in the rules.lua. It's in the dialog rules. Set backdrop to false.

**Comment by ilovecookieee** [comment]
Oh I forgot about the screenshot. This setup uses a script I created that handles area screenshot and full screenshot. Put the `snap` to your $PATH. And make sure to install xclip. The rules.lua is in the `awesome/configuration/client/rules.lua` Find the "dialog"  and set drawbackdrop to **false**.

**Comment by iskmar** [comment]
Hm, even though I added snap to $PATH and installed xclip, SS is still not working. 
I added "export PATH=$PATH:/home/user/.bin/snap.sh" to my bashrc file. Tried with /snap as well but to no success either. Am I missing something?

**Comment by ilovecookieee** [comment]
Remove the snap.sh in the path. Just `export PATH=$PATH:$HOME/.bin/`. And the snap accepts parameters which is `full` for fullscreen shot and `area` for area screenshot. Tho it's already configured in keyboard shortcuts.

**Comment by iskmar** [comment]
That did not give back any results.

**Comment by ilovecookieee** [comment]
Did you copy the snap script from `Glorious-Dotfiles/bin/snap` to `$HOME/.bin/`?

**Comment by iskmar** [comment]
yes, I have.

**Comment by ilovecookieee** [comment]
Oof. I usually use `$HOME/.local/bin/` but I tried your `$HOME/.bin/` I move snap to it and add it to $PATH using `export PATH=$PATH:$HOME/.bin/` It worked for me.

**Comment by iskmar** [comment]
Hm, well something is wrong. I'll have a look at it later.

**Comment by ilovecookieee** [comment]
Well, if you're having problem and don't wanna use the `snap` script, just change the keybindings on `$HOME/.config/awesome/configuration/keys/global.lua`. Just search for the *Screen Shots*.

**Comment by iskmar** [comment]
Ok, so $HOME/.bin does not work. So I placed all shell scripts inside $HOME/.local/bin/ as you suggested, and voila, everything is fine now. Thanks for all the help :)
