### ISSUE TITLE
[Rounded] Attempt to index a nil value (field 'first_tag')

### ISSUE THREAD

**Issue by Sventra** [ilovecookieee/Glorious-Dotfiles#4]
Whenever I try to open an image from Telegram Desktop (which opens an image viewer instance) I get this error
`/layout/init.lua:44: attempt to index a nil value (field 'first_tag')`

**Comment by ilovecookieee** [comment]
Reproduced this even using the default `rc.lua`. I'll report this to the developers. As of now, you can use this "fixed" temporarily while waiting on the devs. Replace line 44 in `/layout/init.lua` with
```
    if first_tag then
      c.first_tag.fullscreenMode = c.fullscreen
    end
```
