### ISSUE TITLE
[Lines] [Rounded] Attempt to index nil value bottom_panel

### ISSUE THREAD

**Issue by XeGrox** [ilovecookieee/Glorious-Dotfiles#5]
`/.config/awesome/layout/init.lua:26: attempt to index a nil value (field 'bottom_panel')`
This error only pops up on lines and rounded themes, floppy works gr8 without any errors :)

**Comment by ilovecookieee** [comment]
Pardon me. I will be revising it because of ugly codes lol. It should be finished in a day or two.

**Comment by ilovecookieee** [comment]
fixed it
