### ISSUE TITLE
titlebars_enabled rule does not work 

### ISSUE THREAD

**Issue by XeGrox** [ilovecookieee/Glorious-Dotfiles#6]
I've set the rule to false but the titlebar still remains there. Also, the default rule set for feh disables the titlebar but when the same rule is used for another application (e.g. nm-connection-editor), the titlebar remains.

**Comment by ilovecookieee** [comment]
`awesome/module/titlebar-decorate-client.lua` causes this issue. This is the most 'messiest' code of the setups. You can change the titlebar behaviour there. It's happening because I set all the floating clients to have a titlebar, so just edit the `titlebar-decorate-client.lua`

**Comment by XeGrox** [comment]
The thing is that even though a `titlebars_enabled` is set to false (and it is by default), it is still created and can be shown with `awful.titlebar.show()`, which shouldn't happen since [this line](https://github.com/ilovecookieee/Glorious-Dotfiles/blob/0c21e7f8064e8c9cec679c8dc8ff52c7b0c421a1/config/awesome/rounded/module/titlebar.lua#L58) prevents a titlebar from being created.
 I've tested it by creating a rule for a specific app (using the xprop thing) and it worked, so that's probably the reason. 
A workaround would be creating a 0 width titlebar for applications where a titlebar isn't needed.
Another way would be removing all instances of `awful.titlebar.show/hide` in `titlebar-decorate-client.lua` and creating a `titlebars_enabled = true` rule for all applications and exclude those you don't want in `exclude_any {}`, but then you'll be unable to hide titlebars when switching between layouts. ¯\_(ツ)_/¯

Sorry if you don't understand, I think I'm having problems expressing myself too :p

**Comment by ilovecookieee** [comment]
Hey I tried your PR and it works perfectly. I added this line btw inside the `c.floating` block to check the `titlebars_enabled`.
```
      -- Hide titlebar if titlebars_enabled is false in rules
      if not c.titlebars_enabled  then
        awful.titlebar.hide(c, 'left')
      end
```

**Comment by XeGrox** [comment]
aa6c87fd
