### ISSUE TITLE
attempt to call/index a nil value

### ISSUE THREAD

**Issue by anselal** [ilovecookieee/Glorious-Dotfiles#7]
Hi there,

I am new to awesomewm and try to install your floppy configuration. I have install all the recommended packages on Ubuntu 18.04.3 and I get the following 2 errors when I restart awesomewm:

`~/.config/module/notifications.lua:115 attempt to call a nil value (field 'connect_signal')`

`~/.config/layout/init.lua:25 attempt to index a nil value (field 'top_panel')`

Do you have any idea what could cause this ?

**Comment by ilovecookieee** [comment]
Make sure that you're using the git branch of awesome :)

**Comment by anselal** [comment]
Oh, I saw that you mentioned the git version but I thought that it didn't matter because I try to install it on a Ubuntu 18.04 VM.

Unfortunately I cannot find all the required packages...

**Comment by anselal** [comment]
Thank you for the feedback. Managed to run it. Looks great but everything seems broken. Gotta figure out why.

**Comment by ilovecookieee** [comment]
Yep, it will only run on the git-master branch version. And btw, I just updated the configs, it should fix the errors now.

**Comment by anselal** [comment]
Still the UI breaks, maybe it is a resolution thing as you mentioned in the docs.
Or it tries to load some things that aren't there.
eg. the left menu opens ok but when I close it it just breaks.

Will try to install it on my x220 to see how it goes.

**Comment by ilovecookieee** [comment]
What do you mean by UI breaks? Can you please send a screenshot or something?

**Comment by anselal** [comment]
This happens when I close the left panel

![2019-11-29_10h12_13](https://user-images.githubusercontent.com/8732668/69854027-ba651a00-1290-11ea-9d6b-1139cefa1d0a.png)

don't know why this happens but I guess it is something in my installation and not in your config.
Also the UI elements in the left panel are not responding well in my installation.
eg. the volume indicator does not move when I click on it. When I reopen the panel I see the change

**Comment by ilovecookieee** [comment]
Welp, it looks like a graphical issue to me, buddy. Make sure to install the latest drivers and use a compositor if you're not using any.

**Comment by anselal** [comment]
thnx. a compositor like compiz or compton ? what do you suggest ?

**Comment by ilovecookieee** [comment]
Use [compton-tryone](https://github.com/tryone144/compton) fork so you will have a blur effect.

**Comment by anselal** [comment]
another issue is that when I press the web search in the sidebar it says that it cannot find the file `rofi-web-search.py` although it exists in the specified folder.

PS: sorry for bothering you

**Comment by ilovecookieee** [comment]
Oh, it's okay. Install python3. Make sure to install the required dependencies listed in the Readme

**Comment by anselal** [comment]
python 3 is already installed and all the other dependencies also...

with check them again after work and I'll post some feedback

**Comment by anselal** [comment]
Still the same issue. Also when I open the terminal I cannot write anything. The system lags...

**Comment by ilovecookieee** [comment]
Sorry but I can't reproduce your problem so I can't really help you. It works perfectly fine in my end.

**Comment by anselal** [comment]
Sorry for not giving you more details about my problem. I will figure it out eventually
