### ISSUE TITLE
Rounded Awesome Theme Errors on Manjaro

### ISSUE THREAD

**Issue by RD1K** [ilovecookieee/Glorious-Dotfiles#8]
Hi! First of all, I'd like to say that I think your Awesome themes are absolutely beautiful and I'm really looking forward to being able to use them. I actually installed Awesome only because I saw some of your themes over on Reddit at r/unixporn.

Anyway, I tried installing your Rounded Awesome theme on my PC running Manjaro Linux, but I had a few error messages appear when I refreshed Awesome:
```
Oops, an error happened!
/home/<username>/.config/awesome/module/notifications.lua:115: attempt to call a nil value (field 'connect_signal')
```
```
Oops, there were errors during startup!
error while running function!
stack traceback:
    /home/<username>/.config/awesome/module/notifications.lua:115: in main chunk
    [C]: in function 'require'
    /home/<username>/.config/awesome/rc.lua:25: in main chunk
error: /home/<username>/.config/awesome/module/notifications.lua:115: attempt to call a nil value (field 'connect_signal')
```
```
Oops, an error happened!
/home/<username>/.config/awesome/layout/init.lua:22: attempt to index a nil value (field 'bottom_panel')
```
```
Oops, an error happened!
/home/<username>/.config/awesome/layout/init.lua:22: attempt to index a nil value (field 'bottom_panel')
```

What can I do to fix this, or is it a bug? Thanks in advance.

**Comment by ilovecookieee** [comment]
Thank you for the compliments! Anyway, make sure that you're using the git branch of awesome. :) In Arch you can install it by `yay -S awesome-git` so I think you can also do that in Manjaro with any aur helpers.

**Comment by RD1K** [comment]
Thank you so much, it works straight away with awesome-git!

**Comment by RD1K** [comment]
Actually, I'm still facing a similar issue on the Rounded theme. I see this:
```
Oops, an error happened!
/home/<username/.config/awesome/widget/notifications center/init.lua:-36: attempt to index a nil value (field 'right_panel')
```

**Comment by ilovecookieee** [comment]
Oof. I just forgot to push the update. Thanks for reporting it. Anyway, I already pushed the update/fix, it should work now.
