### ISSUE TITLE
[Rounded] Notification panel not launching

### ISSUE THREAD

**Issue by XeGrox** [ilovecookieee/Glorious-Dotfiles#9]
`error: .../.config/awesome/widget/notification-center/init.lua:36: attempt to index a nil value (field 'right_panel')`

**Comment by ilovecookieee** [comment]
Still not working?

**Comment by XeGrox** [comment]
Yep

**Comment by ilovecookieee** [comment]
Weird, it's working on my end. Are you using the latest update?

**Comment by XeGrox** [comment]
Yep, tested the pure config on xephyr too.
It's working on floppy but not rounded dunno bout lines.

**Comment by ilovecookieee** [comment]
Oof. Okay I'll check it on a VM.

**Comment by XeGrox** [comment]
Uhh found out its because u added the `weather-update.lua` file in `.gitignore` ...

**Comment by ilovecookieee** [comment]
Oh shoot. I'm stupid af. Sorry mate. I'll fix it now

**Comment by XeGrox** [comment]
70d3124
